/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FNt_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};

static const casadi_real casadi_c0[2] = {1., 0.};
static const casadi_real casadi_c1[4] = {1., 0., 0., 1.};

/* f_rhs:(i0[7],i1[2])->(o0[7]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, *w2=w+4, *w3=w+6, w4, *w5=w+11, w6, w7, *w8=w+20, *w9=w+22, *w10=w+24, *w11=w+28;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #2: @2 = [[1, 0]] */
  casadi_copy(casadi_c0, 2, w2);
  /* #3: @3 = 
  [[1, 0], 
   [0, 1]] */
  casadi_copy(casadi_c1, 4, w3);
  /* #4: @4 = -0.342 */
  w4 = -3.4200000000000003e-01;
  /* #5: @5 = input[0][0] */
  casadi_copy(arg[0], 7, w5);
  /* #6: @6 = @5[0] */
  for (rr=(&w6), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #7: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #8: @4 = (@4*@6) */
  w4 *= w6;
  /* #9: @6 = 1.08 */
  w6 = 1.0800000000000001e+00;
  /* #10: @4 = (@4/@6) */
  w4 /= w6;
  /* #11: @6 = @5[0] */
  for (rr=(&w6), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #12: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #13: @7 = 1.08 */
  w7 = 1.0800000000000001e+00;
  /* #14: @6 = (@6/@7) */
  w6 /= w7;
  /* #15: @8 = horzcat(@4, @6) */
  rr=w8;
  *rr++ = w4;
  *rr++ = w6;
  /* #16: @8 = @8' */
  /* #17: @4 = 0.342 */
  w4 = 3.4200000000000003e-01;
  /* #18: @6 = @5[0] */
  for (rr=(&w6), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #19: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #20: @4 = (@4*@6) */
  w4 *= w6;
  /* #21: @6 = @5[0] */
  for (rr=(&w6), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #22: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #23: @9 = horzcat(@4, @6) */
  rr=w9;
  *rr++ = w4;
  *rr++ = w6;
  /* #24: @9 = @9' */
  /* #25: @10 = horzcat(@8, @9) */
  rr=w10;
  for (i=0, cs=w8; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<2; ++i) *rr++ = *cs++;
  /* #26: @11 = @10' */
  for (i=0, rr=w11, cs=w10; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #27: @3 = (@3-@11) */
  for (i=0, rr=w3, cs=w11; i<4; ++i) (*rr++) -= (*cs++);
  /* #28: @1 = mac(@2,@3,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w3+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #29: @2 = input[1][0] */
  casadi_copy(arg[1], 2, w2);
  /* #30: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #31: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #32: @0 = 0 */
  w0 = 0.;
  /* #33: @1 = [[1, 0]] */
  casadi_copy(casadi_c0, 2, w1);
  /* #34: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #35: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #36: @0 = 0 */
  w0 = 0.;
  /* #37: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #38: @8 = [[1, 0]] */
  casadi_copy(casadi_c0, 2, w8);
  /* #39: @1 = mac(@8,@11,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w8+j, tt=w11+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #40: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #41: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #42: @0 = 0 */
  w0 = 0.;
  /* #43: @4 = 0 */
  w4 = 0.;
  /* #44: @6 = @5[1] */
  for (rr=(&w6), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #45: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #46: @1 = horzcat(@4, @6) */
  rr=w1;
  *rr++ = w4;
  *rr++ = w6;
  /* #47: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #48: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  /* #49: @0 = 0 */
  w0 = 0.;
  /* #50: @4 = 0 */
  w4 = 0.;
  /* #51: @6 = @5[1] */
  for (rr=(&w6), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #52: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #53: @1 = horzcat(@4, @6) */
  rr=w1;
  *rr++ = w4;
  *rr++ = w6;
  /* #54: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #55: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  /* #56: @0 = 0 */
  w0 = 0.;
  /* #57: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #58: @4 = 0 */
  w4 = 0.;
  /* #59: @6 = @5[2] */
  for (rr=(&w6), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #60: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #61: @8 = horzcat(@4, @6) */
  rr=w8;
  *rr++ = w4;
  *rr++ = w6;
  /* #62: @1 = mac(@8,@11,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w8+j, tt=w11+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #63: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #64: output[0][5] = @0 */
  if (res[0]) res[0][5] = w0;
  /* #65: @0 = 0 */
  w0 = 0.;
  /* #66: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #67: @4 = 0 */
  w4 = 0.;
  /* #68: @6 = @5[2] */
  for (rr=(&w6), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  /* #69: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #70: @8 = horzcat(@4, @6) */
  rr=w8;
  *rr++ = w4;
  *rr++ = w6;
  /* #71: @1 = mac(@8,@11,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w8+j, tt=w11+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #72: @0 = mac(@1,@2,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #73: output[0][6] = @0 */
  if (res[0]) res[0][6] = w0;
  return 0;
}

/* FNt:(i0[7],i1[2])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+2, *cr, *cs;
  casadi_real *w0=w+32, w1, w2, *w3=w+41, *w4=w+43, *w5=w+45, w6, w7, w8, *w9=w+52, *w10=w+54, *w11=w+56, *w12=w+60, w13, w14, w15, w16, w17, *w18=w+69, *w19=w+76, *w20=w+83;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 7, w0);
  /* #1: @1 = 0.00833333 */
  w1 = 8.3333333333333332e-03;
  /* #2: @2 = 0 */
  w2 = 0.;
  /* #3: @3 = zeros(1x2) */
  casadi_clear(w3, 2);
  /* #4: @4 = [[1, 0]] */
  casadi_copy(casadi_c0, 2, w4);
  /* #5: @5 = 
  [[1, 0], 
   [0, 1]] */
  casadi_copy(casadi_c1, 4, w5);
  /* #6: @6 = -0.342 */
  w6 = -3.4200000000000003e-01;
  /* #7: @7 = @0[0] */
  for (rr=(&w7), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #8: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #9: @6 = (@6*@7) */
  w6 *= w7;
  /* #10: @7 = 1.08 */
  w7 = 1.0800000000000001e+00;
  /* #11: @6 = (@6/@7) */
  w6 /= w7;
  /* #12: @7 = @0[0] */
  for (rr=(&w7), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #13: @7 = sin(@7) */
  w7 = sin( w7 );
  /* #14: @8 = 1.08 */
  w8 = 1.0800000000000001e+00;
  /* #15: @7 = (@7/@8) */
  w7 /= w8;
  /* #16: @9 = horzcat(@6, @7) */
  rr=w9;
  *rr++ = w6;
  *rr++ = w7;
  /* #17: @9 = @9' */
  /* #18: @6 = 0.342 */
  w6 = 3.4200000000000003e-01;
  /* #19: @7 = @0[0] */
  for (rr=(&w7), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #20: @7 = sin(@7) */
  w7 = sin( w7 );
  /* #21: @6 = (@6*@7) */
  w6 *= w7;
  /* #22: @7 = @0[0] */
  for (rr=(&w7), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #23: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #24: @10 = horzcat(@6, @7) */
  rr=w10;
  *rr++ = w6;
  *rr++ = w7;
  /* #25: @10 = @10' */
  /* #26: @11 = horzcat(@9, @10) */
  rr=w11;
  for (i=0, cs=w9; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<2; ++i) *rr++ = *cs++;
  /* #27: @12 = @11' */
  for (i=0, rr=w12, cs=w11; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #28: @5 = (@5-@12) */
  for (i=0, rr=w5, cs=w12; i<4; ++i) (*rr++) -= (*cs++);
  /* #29: @3 = mac(@4,@5,@3) */
  for (i=0, rr=w3; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w4+j, tt=w5+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #30: @4 = input[1][0] */
  casadi_copy(arg[1], 2, w4);
  /* #31: @2 = mac(@3,@4,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w4+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #32: @6 = 0 */
  w6 = 0.;
  /* #33: @3 = [[1, 0]] */
  casadi_copy(casadi_c0, 2, w3);
  /* #34: @6 = mac(@3,@4,@6) */
  for (i=0, rr=(&w6); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w4+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #35: @7 = 0 */
  w7 = 0.;
  /* #36: @3 = zeros(1x2) */
  casadi_clear(w3, 2);
  /* #37: @9 = [[1, 0]] */
  casadi_copy(casadi_c0, 2, w9);
  /* #38: @3 = mac(@9,@12,@3) */
  for (i=0, rr=w3; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w9+j, tt=w12+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #39: @7 = mac(@3,@4,@7) */
  for (i=0, rr=(&w7); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w4+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #40: @8 = 0 */
  w8 = 0.;
  /* #41: @13 = 0 */
  w13 = 0.;
  /* #42: @14 = @0[1] */
  for (rr=(&w14), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #43: @14 = cos(@14) */
  w14 = cos( w14 );
  /* #44: @3 = horzcat(@13, @14) */
  rr=w3;
  *rr++ = w13;
  *rr++ = w14;
  /* #45: @8 = mac(@3,@4,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w4+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #46: @13 = 0 */
  w13 = 0.;
  /* #47: @14 = 0 */
  w14 = 0.;
  /* #48: @15 = @0[1] */
  for (rr=(&w15), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #49: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #50: @3 = horzcat(@14, @15) */
  rr=w3;
  *rr++ = w14;
  *rr++ = w15;
  /* #51: @13 = mac(@3,@4,@13) */
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w4+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #52: @14 = 0 */
  w14 = 0.;
  /* #53: @3 = zeros(1x2) */
  casadi_clear(w3, 2);
  /* #54: @15 = 0 */
  w15 = 0.;
  /* #55: @16 = @0[2] */
  for (rr=(&w16), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #56: @16 = cos(@16) */
  w16 = cos( w16 );
  /* #57: @9 = horzcat(@15, @16) */
  rr=w9;
  *rr++ = w15;
  *rr++ = w16;
  /* #58: @3 = mac(@9,@12,@3) */
  for (i=0, rr=w3; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w9+j, tt=w12+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #59: @14 = mac(@3,@4,@14) */
  for (i=0, rr=(&w14); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w4+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #60: @15 = 0 */
  w15 = 0.;
  /* #61: @3 = zeros(1x2) */
  casadi_clear(w3, 2);
  /* #62: @16 = 0 */
  w16 = 0.;
  /* #63: @17 = @0[2] */
  for (rr=(&w17), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #64: @17 = sin(@17) */
  w17 = sin( w17 );
  /* #65: @9 = horzcat(@16, @17) */
  rr=w9;
  *rr++ = w16;
  *rr++ = w17;
  /* #66: @3 = mac(@9,@12,@3) */
  for (i=0, rr=w3; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w9+j, tt=w12+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #67: @15 = mac(@3,@4,@15) */
  for (i=0, rr=(&w15); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w4+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #68: @18 = vertcat(@2, @6, @7, @8, @13, @14, @15) */
  rr=w18;
  *rr++ = w2;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  /* #69: @2 = 0.025 */
  w2 = 2.5000000000000001e-02;
  /* #70: @19 = (@2*@18) */
  for (i=0, rr=w19, cs=w18; i<7; ++i) (*rr++)  = (w2*(*cs++));
  /* #71: @19 = (@0+@19) */
  for (i=0, rr=w19, cr=w0, cs=w19; i<7; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #72: @20 = f_rhs(@19, @4) */
  arg1[0]=w19;
  arg1[1]=w4;
  res1[0]=w20;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #73: @19 = (2.*@20) */
  for (i=0, rr=w19, cs=w20; i<7; ++i) *rr++ = (2.* *cs++ );
  /* #74: @18 = (@18+@19) */
  for (i=0, rr=w18, cs=w19; i<7; ++i) (*rr++) += (*cs++);
  /* #75: @2 = 0.025 */
  w2 = 2.5000000000000001e-02;
  /* #76: @20 = (@2*@20) */
  for (i=0, rr=w20, cs=w20; i<7; ++i) (*rr++)  = (w2*(*cs++));
  /* #77: @20 = (@0+@20) */
  for (i=0, rr=w20, cr=w0, cs=w20; i<7; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #78: @19 = f_rhs(@20, @4) */
  arg1[0]=w20;
  arg1[1]=w4;
  res1[0]=w19;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #79: @20 = (2.*@19) */
  for (i=0, rr=w20, cs=w19; i<7; ++i) *rr++ = (2.* *cs++ );
  /* #80: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<7; ++i) (*rr++) += (*cs++);
  /* #81: @2 = 0.05 */
  w2 = 5.0000000000000003e-02;
  /* #82: @19 = (@2*@19) */
  for (i=0, rr=w19, cs=w19; i<7; ++i) (*rr++)  = (w2*(*cs++));
  /* #83: @19 = (@0+@19) */
  for (i=0, rr=w19, cr=w0, cs=w19; i<7; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #84: @20 = f_rhs(@19, @4) */
  arg1[0]=w19;
  arg1[1]=w4;
  res1[0]=w20;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #85: @18 = (@18+@20) */
  for (i=0, rr=w18, cs=w20; i<7; ++i) (*rr++) += (*cs++);
  /* #86: @18 = (@1*@18) */
  for (i=0, rr=w18, cs=w18; i<7; ++i) (*rr++)  = (w1*(*cs++));
  /* #87: @0 = (@0+@18) */
  for (i=0, rr=w0, cs=w18; i<7; ++i) (*rr++) += (*cs++);
  /* #88: output[0][0] = @0 */
  casadi_copy(w0, 7, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int FNt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int FNt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int FNt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FNt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int FNt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FNt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void FNt_incref(void) {
}

CASADI_SYMBOL_EXPORT void FNt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int FNt_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int FNt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real FNt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FNt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FNt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FNt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FNt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int FNt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 90;
  return 0;
}

CASADI_SYMBOL_EXPORT int FNt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 90*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_FNt(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[106];
  casadi_int *iw = 0;
  const casadi_real* arg[9] = {0};
  casadi_real* res[3] = {0};
  if (argc>2) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"FNt\" failed. Too many input arguments (%d, max 2)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"FNt\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+16);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+7, casadi_s1, w+16);
  --resc;
  res[0] = w+9;
  FNt_incref();
  mem = FNt_checkout();
  i = FNt(arg, res, iw, w+16, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"FNt\" failed.");
  FNt_release(mem);
  FNt_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s0, res[0]);
}
#endif

casadi_int main_FNt(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[106];
  const casadi_real* arg[9];
  casadi_real* res[3];
  arg[0] = w+0;
  arg[1] = w+7;
  res[0] = w+9;
  a = w;
  for (j=0; j<9; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = FNt(arg, res, iw, w+16, 0);
  if (flag) return flag;
  r = w+9;
  for (j=0; j<7; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[4];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_FNt(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "FNt")==0) {
    mex_FNt(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'FNt'");
}
#endif
CASADI_SYMBOL_EXPORT int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "FNt")==0) {
    return main_FNt(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'FNt'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
